project_id = "gszsufxjstgpsxikgeeb"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-find-user-by-email]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.test-connection]
verify_jwt = false

[functions.terminal-proxy]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = true

[functions.check-capacity-alerts]
verify_jwt = false

[functions.system-chat]
verify_jwt = true

[functions.check-ticket-deadlines]
verify_jwt = false

[functions.go2rtc-proxy]
verify_jwt = true

[functions.go2rtc-hls-proxy]
verify_jwt = false

[functions.go2rtc-webrtc-proxy]
verify_jwt = true

[functions.hls-proxy]
verify_jwt = false

[functions.monitor-proxy]
verify_jwt = true

[functions.check-device-status]
verify_jwt = false

[functions.grafana-proxy]
verify_jwt = true

[functions.sync-all-devices]
verify_jwt = false

[functions.sync-zabbix-data]
verify_jwt = false
