project_id = "gszsufxjstgpsxikgeeb"

[functions.admin-list-users]
verify_jwt = true

[functions.admin-find-user-by-email]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.test-connection]
verify_jwt = false

[functions.terminal-proxy]
verify_jwt = false
